### ISSUE TITLE
Crash during init

### ISSUE THREAD

**Issue by Krutonium** [IronManMark20/ShellSharp#1]
Line 19 of Program.cs
Name = fileInfo.Name.Remove(fileInfo.Name.Length - fileInfo.Extension.Length);
System.ArgumentOutOfRangeException was unhandled by user code
HResult=-2146233086
Message=startIndex must be less than length of string.
Parameter name: startIndex
ParamName=startIndex
Source=mscorlib
StackTrace:
at System.String.Remove(Int32 startIndex)
at MerulaShellProgramManager.programs.Program..ctor(FileInfo fileInfo) in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellProgramManager\programs\Program.cs:line 19
at MerulaShellProgramManager.ProgramList.LoadDirectory(String directory) in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellProgramManager\ProgramList.cs:line 46
at MerulaShellProgramManager.ProgramList.LoadIoItems() in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellProgramManager\ProgramList.cs:line 26
at MerulaShellProgramManager.ProgramList..ctor(String[] directories) in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellProgramManager\ProgramList.cs:line 17
at MerulaShellProgramManager.ProgramManager.GetDesktopItems() in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellProgramManager\ProgramManager.cs:line 15
at MerulaShellController.ManagePrograms.GetPrograms.GetDesktopItems() in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellController\ManagePrograms\GetPrograms.cs:line 18
at MerulaShellUi.Desktop.LoadButtons() in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellUi\Desktop.xaml.cs:line 55
at MerulaShellUi.Desktop..ctor() in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellUi\Desktop.xaml.cs:line 28
at MerulaShellUi.TaskWindow..ctor() in C:\Users\pfckr\Source\Repos\ShellSharp\MerulaShellUi\TaskWindow.xaml.cs:line 36

**Comment by emmatyping** [comment]
I am taking a guess that the problem is that there is a file that doesn't have an extension or has only an extension.

try replacing like this:

```
public Program(FileInfo fileInfo)
        {
            this.fileInfo = fileInfo;
            try
            {
                Name = fileInfo.Name.Remove(fileInfo.Name.Length - fileInfo.Extension.Length);
            }
            catch (ArgumentOutOfRangeException)
            {
                Debug.WriteLine("Skipping file without extension:  " + fileInfo.Name);
                Name = "";
            }

            Path = fileInfo.FullName;
        } 
```

**Comment by Krutonium** [comment]
Can confirm that worked,

```
Event Type  Event   Time    Duration    Thread  Detail Description
Program Output  Skipping file without extension:  null  0.29s
```
